### ISSUE TITLE
MongoDB module

### ISSUE THREAD

**Issue by Adito5393** [decebals/dada#2]
Could someone (maybe @decebals?!) share his/her test project used for the other 2 modules available (csv and iciql)? I would like to develop a similar module for MongoDB using the [Morphia](https://morphia.dev/2.0.0-RC1/) library, which is build on top of the Java driver. 

Having the unit test templates will speed up the development time and hopefully, I will be able to submit a PR soon.

**Comment by decebals** [comment]
I used this library only for [Matilda](https://github.com/pippo-java/matilda), that is a [Pippo](http://pippo.ro).
I think the goal of the project is interesting, but unfortunately it did not catch the attention of several developers.

**Comment by Adito5393** [comment]
Thanks for the fast reply. Unfortunately, I don't have the time now to develop the module, therefore, I will close the issue and in the future, I will send a PR with the MongoDB module.
